### ISSUE TITLE
一个activity里面有多个Store怎么办？

### ISSUE THREAD

**Issue by JackZhous** [JohnnyShieh/RxFlux#1]
我的想法是按照业务划分，比如一个activity有下载文件任务，又有更新其他数据的任务，我就弄成两个store，但是这样的话这个activity只能实现一个StoreObserver<T>，那我的两个Store怎么把业务数据通知给Activity呢？

**Comment by JohnnyShieh** [comment]
第一个问题：store 的划分方法？
在你这个 activity 中，首先有两种任务，下载任务和更新其他数据
那么以业务划分的应该是 action， DownloadAction 和 UpdateDataAction，而在 Flux 架构中，Store 是维护视图状态的，store 是以有一定逻辑关系的视图状态集合来划分，的确在这个场景中应该有 DownloadStore 和 XXDataStore。但是 Store 是以数据的逻辑关系为划分准则的，试想一下，还有另外一个对下载文件操作的任务，这时不需要再添加一个 store，只需要 DownloadStore ，它维护了下载数据的状态。

第二个问题：activity 可以实现多个 StoreObserver
当一个 activity 或 fragment 有多个 store 时，每个 store 的 event 应该不同实现（event extends StoreChangeEvent），那么上面场景中的 store 应该是 `DownloadStore<DowanloadChangeEvent>` 和 `XXDataStore<XXDataChangeEvent>`。
activity 需要实现 `StoreObserver<DowanloadChangeEvent>` 和 `XXDataStore<XXDataChangeEvent>`

**Comment by JackZhous** [comment]
你的第二个回答，当我的activity同时实现了两个StoreObserver这样会出错，比如：class MainActivty implements StoreObserver<StoreChanges.MapStore>,
                   StoreObserver<StoreChanges.BoxDataStore>{}

错误是：
Duplicate class:'com.johnny.rxflux.StoreObserver',就是说出现实现了两个相同的接口，解决办法我想的就是在写一个匿名内部类，让另一个Store去register这个内部类即可，除了这种还有其他的解决办法吗

**Comment by JohnnyShieh** [comment]
非常感谢你发现的这个问题，一开始这么设计是想不同的 event 可以在不同的方法中处理，没想到竟然有低级的语法问题，我会紧急修复这个 bug。
再次感谢 @JackZhous ，Tks

**Comment by JohnnyShieh** [comment]
Java 不支持实现两个不同泛型的相同接口的话，Store 和 StoreObserver 就没必要使用范性了，activity 在 onChange 中只能使用 if-else 语句来区分不同的 store 和 action 引发的变化

具体的改动， @JackZhous 可以看我最新的提交
